### ISSUE TITLE
output goes into wrong place, lacks path

### ISSUE THREAD

**Issue by wkearney99** [davidsuran/WebpConverter#1]
It seems like you're not indicating where the output file should be going.  You're just using the filename location and if they're a series of files from different locations the output will not track with the inputs.

Try this.  Have a series of folders with webp files in them.  Use the File Explorer to search for all webp files from a parent.  Drag/drop those found webp files into your program.  The results will be incorrect.  You'll get all the conversions dumped into the FIRST directory.

I found this solved the problem for me:

`            string outFile = FormattableString.Invariant($"{Path.GetDirectoryName(path)}{Path.DirectorySeparatorChar}{Path.GetFileNameWithoutExtension(path)}.jpg");
`

**Comment by davidsuran** [comment]
Thanks I fixed it in 4cca4e5e2de309e5bfed665e1a11e6605f79a5e8
